### ISSUE TITLE
"Migrations" -- invalid argument 0: json: cannot unmarshal invalid hex string into Go value of type hexutil.Bytes.

### ISSUE THREAD

**Issue by dadaphl** [critesjosh/hello_contract-truffle#2]
I followed the tutorial on 
https://docs.celo.org/developer-guide/start/hello-contract-remote-node
when i run the migration to alfajores i get the following error
```
➜  hello_contract-truffle git:(master) ✗ truffle migrate --network alfajores

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'alfajores'
> Network id:      44787
> Block gas limit: 0 (0x0)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- invalid argument 0: json: cannot unmarshal invalid hex string into Go value of type hexutil.Bytes.

    at /home/philipp/.nvm/versions/node/v14.18.0/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Migration._deploy (/home/philipp/.nvm/versions/node/v14.18.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:70:1)
    at Migration._load (/home/philipp/.nvm/versions/node/v14.18.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:56:1)
    at Migration.run (/home/philipp/.nvm/versions/node/v14.18.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (/home/philipp/.nvm/versions/node/v14.18.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/home/philipp/.nvm/versions/node/v14.18.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/home/philipp/.nvm/versions/node/v14.18.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/home/philipp/.nvm/versions/node/v14.18.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:258:1)
    at Object.run (/home/philipp/.nvm/versions/node/v14.18.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
    at Command.run (/home/philipp/.nvm/versions/node/v14.18.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)
Truffle v5.4.14 (core: 5.4.14)
Node v14.18.0
➜  hello_contract-truffle git:(master) ✗
```

env
```
➜  hello_contract-truffle git:(master) ✗ node -v
v14.18.0
➜  hello_contract-truffle git:(master) ✗ which node
/home/philipp/.nvm/versions/node/v14.18.0/bin/node
➜  hello_contract-truffle git:(master) ✗ truffle version
Truffle v5.4.14 (core: 5.4.14)
Solidity v0.5.16 (solc-js)
Node v14.18.0
Web3.js v1.5.3
➜  hello_contract-truffle git:(master) ✗ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
➜  hello_contract-truffle git:(master) ✗
```

**Comment by critesjosh** [comment]
Thanks for flagging this. I ran into this as well. Try uninstalling truffle `npm uninstall -g truffle` and reinstalling it at version 5.4.0 with `npm install -g truffle@5.4.0`. I am chatting with the truffle team to try to determine the cause of this error. I will update the tutorial in the meantime.

**Comment by dadaphl** [comment]
Thanks, that solved the issue for me.

**Comment by ahmeddrawy** [comment]
I have the same error with truffle `5.4.24`

**Comment by critesjosh** [comment]
@ahmeddrawy can you try using version `5.4.0`

**Comment by viraj124** [comment]
@critesjosh I face the same with 5.4.26 can this be fixed ?

**Comment by critesjosh** [comment]
I found the source of this bug. Truffle doesn't estimate the gas properly, so you need to specify a gas limit in `truffle.config.js`. This should work with all versions of truffle.

```js
// truffle.config.js
const ContractKit = require('@celo/contractkit')
const Web3 = require('web3')
require('dotenv').config()
const web3 = new Web3('https://alfajores-forno.celo-testnet.org')
const kit = ContractKit.newKitFromWeb3(web3)
kit.connection.addAccount(process.env.PRIVATE_KEY)

module.exports = {
  networks: {
    test: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*"
    },
    alfajores: {
      provider: kit.connection.web3.currentProvider, // CeloProvider
      network_id: 44787,                   // latest Alfajores network id
      gas: 4000000,    // Gas limit used for deploys, truffle gas estimation doesn't work work so we have to hardcode it
    }
...
   ```

**Comment by viraj124** [comment]
Thanks a lot @critesjosh  it worked for me

**Comment by lopeselio** [comment]
This is a golden fix @critesjosh
